apiVersion: apps/v1
kind: Deployment
metadata:
  name: user09
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user09
  template:
    metadata:
      labels:
        app: user09
    spec:
      containers:
        - name: user09-server
          image: ghcr.io/brovonthep/bj
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user09-service
  labels:
    app: user09-service
spec:
  selector:
    app: user09-world
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP
