apiVersion: apps/v1
kind: Deployment
metadata:
  name: bj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bj
  template:
    metadata:
      labels:
        app: bj
    spec:
      containers:
        - name: hello-world-server
          image: ghcr.io/brovonthep/bj
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    app: hello-service
spec:
  selector:
    app: hello-world
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP